# embed_binary(INPUT OUTPUT SYMBOL)
#
# Generates a C++ translation unit at OUTPUT that exposes the bytes of INPUT
# as two extern symbols:
#
#   extern const unsigned char  ${SYMBOL}[];
#   extern const unsigned long  ${SYMBOL}_size;
#
# The generated file is written eagerly at configure time. Chunked APPEND
# keeps peak CMake string memory bounded for multi-MB blobs (the network
# file is ~16 MB).
#
# Only re-emits if INPUT is newer than OUTPUT.

function(embed_binary INPUT_FILE OUTPUT_FILE SYMBOL_NAME)
    if (NOT EXISTS "${INPUT_FILE}")
        message(FATAL_ERROR "embed_binary: source not found: ${INPUT_FILE}")
    endif()

    if (EXISTS "${OUTPUT_FILE}")
        file(TIMESTAMP "${INPUT_FILE}"  in_ts  "%s")
        file(TIMESTAMP "${OUTPUT_FILE}" out_ts "%s")
        if (NOT in_ts STREQUAL "" AND NOT out_ts STREQUAL "" AND NOT in_ts GREATER out_ts)
            return()
        endif()
    endif()

    message(STATUS "embed_binary: generating ${OUTPUT_FILE} from ${INPUT_FILE}")

    file(READ "${INPUT_FILE}" hex_data HEX)
    string(LENGTH "${hex_data}" hex_len)
    math(EXPR byte_count "${hex_len} / 2")

    # `extern` is mandatory: namespace-scope `const` has INTERNAL linkage in
    # C++ by default — `extern "C"` only affects name mangling, not linkage.
    # Without `extern`, the symbol is hidden and the linker discards the
    # whole array as unused, leaving the consumer with "undefined reference".
    file(WRITE "${OUTPUT_FILE}"
        "// AUTOGENERATED by embed_binary() — do not edit.\n"
        "#include <cstddef>\n\n"
        "extern \"C\" {\n"
        "alignas(64) extern const unsigned char ${SYMBOL_NAME}[];\n"
        "alignas(64) extern const unsigned char ${SYMBOL_NAME}[] = {\n")

    # Process the hex string in chunks. Each hex chunk of N chars produces
    # N/2 bytes in the output array. 64 KB hex (= 32 KB bytes) per chunk
    # keeps each individual regex/APPEND step quick.
    set(chunk_hex_chars 65536)
    set(offset 0)
    while (offset LESS hex_len)
        math(EXPR remaining "${hex_len} - ${offset}")
        if (remaining LESS chunk_hex_chars)
            set(this_chunk ${remaining})
        else()
            set(this_chunk ${chunk_hex_chars})
        endif()
        string(SUBSTRING "${hex_data}" ${offset} ${this_chunk} chunk)
        string(REGEX REPLACE "(..)" "0x\\1," chunk_arr "${chunk}")
        file(APPEND "${OUTPUT_FILE}" "${chunk_arr}\n")
        math(EXPR offset "${offset} + ${chunk_hex_chars}")
    endwhile()

    file(APPEND "${OUTPUT_FILE}"
        "};\n"
        "extern const unsigned long ${SYMBOL_NAME}_size;\n"
        "extern const unsigned long ${SYMBOL_NAME}_size = ${byte_count}UL;\n"
        "}  // extern \"C\"\n")
endfunction()
