# embed_binary(INPUT OUTPUT SYMBOL)
#
# Generates a small C++ translation unit at OUTPUT that embeds the bytes of
# INPUT into .rodata via the assembler's `.incbin`, exposing:
#
#   extern const unsigned char  ${SYMBOL}[];
#   extern const unsigned long  ${SYMBOL}_size;   // 4-byte size, LLP64-safe
#
# `.incbin` copies the file bytes directly at assemble time — no multi-hundred-MB
# C initializer — so it scales to large nets. (The previous comma-separated
# byte-array TU OOM-killed the compiler around ~69 MB: a 69 MB net expands to a
# ~270 MB source with 69 M array elements.) GCC/Clang assembler only, which is
# the MinGW ship toolchain. The consumer adds INPUT as OBJECT_DEPENDS so a net
# swap re-assembles the TU (the generated .cpp text does not change on swap).

function(embed_binary INPUT_FILE OUTPUT_FILE SYMBOL_NAME)
    if (NOT EXISTS "${INPUT_FILE}")
        message(FATAL_ERROR "embed_binary: source not found: ${INPUT_FILE}")
    endif()

    message(STATUS "embed_binary: generating ${OUTPUT_FILE} (.incbin) from ${INPUT_FILE}")

    # The symbols are defined in inline asm; the C++ declarations give the
    # consumer a typed handle. `.global` + direct-to-exe source (see CMakeLists)
    # keep them from being discarded. Size is `end - start` as a 4-byte `.long`
    # to match `extern const unsigned long` (4 bytes on LLP64 Windows).
    file(WRITE "${OUTPUT_FILE}"
        "// AUTOGENERATED by embed_binary() — do not edit.\n"
        "// Embeds ${INPUT_FILE} into .rodata via assembler .incbin.\n"
        "extern \"C\" {\n"
        "alignas(64) extern const unsigned char ${SYMBOL_NAME}[];\n"
        "extern const unsigned long ${SYMBOL_NAME}_size;\n"
        "}\n\n"
        "__asm__(\n"
        "    \".section .rodata\\n\"\n"
        "    \".balign 64\\n\"\n"
        "    \".global ${SYMBOL_NAME}\\n\"\n"
        "    \"${SYMBOL_NAME}:\\n\"\n"
        "    \".incbin \\\"${INPUT_FILE}\\\"\\n\"\n"
        "    \"${SYMBOL_NAME}_end:\\n\"\n"
        "    \".balign 4\\n\"\n"
        "    \".global ${SYMBOL_NAME}_size\\n\"\n"
        "    \"${SYMBOL_NAME}_size:\\n\"\n"
        "    \".long ${SYMBOL_NAME}_end - ${SYMBOL_NAME}\\n\"\n"
        ");\n")
endfunction()
